# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lfp5hkuFge_S92QCfmwVLcHMDTqTQ6H7
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py 
# import streamlit as st 
# st.markdown(""" This is a Streamlit App """)